In [ ]:
pip install -U fortran-magic

In [ ]:
%reload_ext fortranmagic

/usr/local/lib/python3.6/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [ ]:
import py_compile
%matplotlib inline
%load_ext fortranmagic

import sys;
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))
ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
assert ran_the_first_cell, "Oh noes!"

In [ ]:
x = [10, 'veinte', 30, 40, 50, "sesenta"]
x

[10, 'veinte', 30, 40, 50, 'sesenta']

In [ ]:
primero = x[0]
segundo = x[1]
print("primero:", primero)
print("segundo:", segundo)

primero: 10
segundo: veinte


In [ ]:
ultimo = x[-1]
penultimo = x[-2]
print("Ultimo:", ultimo)
print("Penultimo:", penultimo)

Ultimo: sesenta
Penultimo: 50


In [ ]:
listapeq = x[1:3]
listapeq

['veinte', 30]

In [ ]:
primeros_tres = x[:3]
primeros_tres

[10, 'veinte', 30]

In [ ]:
despues_tres = x[3:]
despues_tres

[40, 50, 'sesenta']

In [ ]:
x = ['avion', 'betun', 'casa', 'dedo', 'emo', 'faro', 'gol','horus']
x[1:7:2]

['betun', 'dedo', 'faro']

In [ ]:
x[::-1]

['horus', 'gol', 'faro', 'emo', 'dedo', 'casa', 'betun', 'avion']

In [ ]:
x = [10, 20, 30, 40, 50]
print("Antes:", x)
x.append('sesenta')
print("Despues:", x)

Antes: [10, 20, 30, 40, 50]
Despues: [10, 20, 30, 40, 50, 'sesenta']


In [ ]:
x = [10, 20, 30, 40, 50]
[y * 2 for y in x]

[20, 40, 60, 80, 100]

In [ ]:
filosofos = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
filosofos

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [ ]:
filosofos['Ludwig'] = 'Wittgenstein'
filosofos

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [ ]:
del filosofos['David']
filosofos

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [ ]:
filosofos['Bertrand':'Immanuel']

TypeError: ignored

In [ ]:
x = [[10, 20, 30],
     [20, 30, 40],
     [50, 60, 70],
     [10, 10, 10]]

y = [[10, 20, 30, 40],
     [20, 30, 40, 50]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [ ]:
%%time

matmul(x, y)

CPU times: user 34 µs, sys: 7 µs, total: 41 µs
Wall time: 44.1 µs


[[500, 800, 1100, 1400],
 [800, 1300, 1800, 2300],
 [1700, 2800, 3900, 5000],
 [300, 500, 700, 900]]

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

matriz = random_matrix(2, 3)
matriz

[[0.9498504990238572, 0.3431313064830879, 0.7590690785744921],
 [0.04248101511162339, 0.8087700034529551, 0.7125633689383942]]

In [ ]:
%%time
randa = random_matrix(1200, 200)
randb = random_matrix(200, 1200)
x = matmul(randa, randb)

CPU times: user 54.9 s, sys: 116 ms, total: 55 s
Wall time: 55.1 s


In [ ]:
def python_producto_punto(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
%%fortran
subroutine fortran_producto_punto(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [ ]:
lista_fecha = [float(i) for i in range(100000)]
arreglo_fecha = np.array(lista_fecha)

In [ ]:
%%time
python_producto_punto(lista_fecha, lista_fecha)

CPU times: user 8.75 ms, sys: 997 µs, total: 9.75 ms
Wall time: 12 ms


333328333350000.0

In [ ]:
%%time
fortran_producto_punto(arreglo_fecha, arreglo_fecha)

CPU times: user 184 µs, sys: 2 µs, total: 186 µs
Wall time: 193 µs


333328333350000.0

In [ ]:
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [ ]:
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [ ]:
import numpy as np

datos = np.array([10, 20, 30, 40])
datos

array([10, 20, 30, 40])

In [ ]:
datos + datos

array([20, 40, 60, 80])

In [ ]:
%%time
# Naive dot product
(arreglo_fecha * arreglo_fecha).sum()

CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 3.17 ms


333328333350000.0

In [ ]:
%%time
# Built-in dot product.
arreglo_fecha.dot(arreglo_fecha)


CPU times: user 2.04 ms, sys: 1.01 ms, total: 3.05 ms
Wall time: 4.36 ms


333328333350000.0

In [ ]:
%%time
fortran_producto_punto(arreglo_fecha, arreglo_fecha)

CPU times: user 202 µs, sys: 0 ns, total: 202 µs
Wall time: 216 µs


333328333350000.0

In [ ]:
# Numpy won't allow us to write a string into an int array.
datos[0] = "foo"

ValueError: ignored

In [ ]:
datos.append(3)

AttributeError: ignored

In [ ]:
dos_pa_dos = datos.reshape(2, 2)
dos_pa_dos

array([[10, 20],
       [30, 40]])

In [ ]:
arreglo = np.array([10, 20, 30, 40, 50, 60], dtype='int16').reshape(2, 3)
print("Arreglo:\n", arreglo, sep='')
print("===========")
print("DType:", arreglo.dtype)
print("Shape:", arreglo.shape)
print("Strides:", arreglo.strides)
print("Datos:", arreglo.data.tobytes())

Arreglo:
[[10 20 30]
 [40 50 60]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Datos: b'\n\x00\x14\x00\x1e\x00(\x002\x00<\x00'


In [ ]:
datos = np.arange(24).reshape(4, 6)
datos

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
datos*datos

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [ ]:
np.sqrt(datos)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152]])

In [ ]:
(datos % 3) == 0

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [ ]:
((datos % 2) == 0) & ((datos % 3) == 0)

array([[ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [ ]:
datos @ datos.T

array([[  55,  145,  235,  325],
       [ 145,  451,  757, 1063],
       [ 235,  757, 1279, 1801],
       [ 325, 1063, 1801, 2539]])

In [ ]:
senos = np.sin(np.linspace(0, 3.14, 10))
cosenos = np.cos(np.linspace(0, 3.14, 10))
senos

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
senos[0]

0.0

In [ ]:
senos[:3]

array([0.        , 0.34185385, 0.64251645])

In [ ]:
senos[5:] 

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
senos[::2] 

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [ ]:
print("senos:\n", senos)
print("senos > 0.5:\n", senos > 0.5)
print("senos[senos > 0.5]:\n", senos[senos > 0.5])

senos:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
senos > 0.5:
 [False False  True  True  True  True  True  True False False]
senos[senos > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [ ]:
print(senos)
senos[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [ ]:
datos_desordenados = np.array([10, 30, 20, 120, -10, 50, 20])

In [ ]:
indices_ordenados = np.argsort(datos_desordenados)
indices_ordenados

array([4, 0, 2, 6, 1, 5, 3])

In [ ]:
datos_desordenados[indices_ordenados]

array([-10,  10,  20,  20,  30,  50, 120])

In [ ]:
capital_mercado = np.array([120, 60, 100, 50, 60])  
Activos = np.array(['Avianca', 'Bahama', 'Call', 'Dino', 'Elmo'])

In [ ]:
sort_by_capmercado = np.argsort(capital_mercado)
Activos[sort_by_capmercado]

array(['Dino', 'Bahama', 'Elmo', 'Call', 'Avianca'], dtype='<U7')

In [ ]:
print("Fechas:\n", repr(event_dates))
print("Valores:\n", repr(event_values))
print("Calendario:\n", repr(calendar))

Fechas:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Valores:
 array([10, 15, 20])
Calendario:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Fechas llenas-adelante:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Fechas llenas-adelante: ['2017-01-06' '2017-01-09' '2017-01-09']


In [ ]:
datos = np.arange(25).reshape(5, 5)
datos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
datos[:2, :2]  

array([[0, 1],
       [5, 6]])

In [ ]:
datos[:2, [0, -1]]

array([[0, 4],
       [5, 9]])

In [ ]:
datos[(datos[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
def varianza(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
varianza(np.random.standard_normal(1000))

0.938822732189381

In [ ]:
datos = np.arange(30)
datos.mean()

14.5

In [ ]:
datos = np.arange(30).reshape(3, 10)
datos

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
datos.mean()

14.5

In [ ]:
datos.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
datos.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [ ]:
fila = np.array([1, 2, 3, 4])
columna = np.array([[1], [2], [3]])
print("Fila:\n", fila, sep='')
print("Columna:\n", columna, sep='')

Fila:
[1 2 3 4]
Columna:
[[1]
 [2]
 [3]]


In [ ]:
fila + columna

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
print("Datos:\n", datos, sep='')
print("Media:\n", datos.mean(axis=0), sep='')
print("Datos - Media:\n", datos - datos.mean(axis=0), sep='')

Datos:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Media:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Datos - Media:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [ ]:
x = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[10, 20, 30, 40, 50])
x

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
print("El indice es:", x.index)
print("Los valores son:", x.values)

El indice es: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Los valores son: [10 20 30 40 50]


In [ ]:
x.iloc[0]

10

In [ ]:
x.loc['a']

10

In [ ]:
x.iloc[:2]

a    10
b    20
dtype: int64

In [ ]:
x.loc[:'c']

a    10
b    20
c    30
dtype: int64

In [ ]:
x.iloc[[0, -1]]

a    10
e    50
dtype: int64

In [ ]:
x.loc[x > 20]

c    30
d    40
e    50
dtype: int64

In [ ]:
otro_x = pd.Series({'a': 100.0, 'c': 200.0, 'd': 300.0, 'z': 400.0})
otro_x

a    100.0
c    200.0
d    300.0
z    400.0
dtype: float64

In [ ]:
x + otro_x

a    110.0
b      NaN
c    230.0
d    340.0
e      NaN
z      NaN
dtype: float64

In [ ]:
(x + otro_x).fillna(0.0)

a    110.0
b      0.0
c    230.0
d    340.0
e      0.0
z      0.0
dtype: float64

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Adj Close 2008-10-14, 116.26, 116.40, 103.14, 104.08, 70749800, 104.08 2008-10-13, 104.55, 110.53, 101.02, 110.26, 54967000, 110.26 2008-10-10, 85.70, 100.00, 85.00, 96.80, 79260700, 96.80 2008-10-09, 93.35, 95.80, 86.60, 88.74, 57763700, 88.74 2008-10-08, 85.91, 96.33, 85.68, 89.79, 78847900, 89.79 2008-10-07, 100.48, 101.50, 88.95, 89.16, 67099000, 89.16 2008-10-06, 91.96, 98.78, 87.54, 98.14, 75264900, 98.14 2008-10-03, 104.00, 106.50, 94.65, 97.07, 81942800, 97.07 2008-10-02, 108.01, 108.79, 100.00.1, 100.10, 57477300, 100.10 2008-10-01, 111.92, 112.36, 107.39, 109.12, 46303000, 109.12 2008-09-30, 108.25, 115.00, 106.30, 113.66, 58095800, 113.66 2008-09-29, 119.62, 119.68, 100.59, 105.26, 93581400, 105.26 2008-09-26, 124.91, 129.80, 123.00, 128.24, 40208700, 128.24 2008-09-25, 129.80.1, 134.79, 128.52, 131.93, 35865600, 131.93 2008-09-24, 127.27, 130.95, 125.15, 128.71, 37393400, 128.71 2008-09-23, 131.85, 135.80, 126.66, ...]
Index: []

[0 rows x 451 columns]

^C
